# version: '3.8'
services:
  coordinator:
    build: ./coordinator
    ports:
      - "8000:8000"
    depends_on:
      - worker1
      - worker2
      - worker3
    volumes:
      - ./scripts:/scripts:ro

  worker1:
    build: ./workers
    command: python w1-BERT.py
    ports:
      - "9001:9001"
    volumes:
      - ./scripts:/scripts:ro

  worker2:
    build: ./workers
    command: python w2-MobileNet.py
    ports:
      - "9002:9002"
    volumes:
      - ./scripts:/scripts:ro

  worker3:
    build: ./workers
    command: python w3-CLIP.py
    ports:
      - "9003:9003"
    volumes:
      - ./scripts:/scripts:ro
